pipeline:
  build:
    image: node:10
    commands:
      - npm install
      - npm run build
      - npm run migrate -- --rebuild
      - npm run migrate
      - npm test

services:
  database:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=online.fdm.center
      - MYSQL_ROOT_PASSWORD=123321Aa
