pipeline:
  build:
    image: node:10
    commands:
      - npm install
      - npm run build
      - sleep 10
      - npm run migrate -- --rebuild
      - npm run migrate
      - npm test
    environment:
      - SERVER_AUTH_TOKEN=testServerAuthToken
      - MYSQL_URL=mysql://root:123321Aa@database/online.fdm.center

services:
  database:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=online.fdm.center
      - MYSQL_ROOT_PASSWORD=123321Aa
