version: '3.1'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /opt/fdm_mysqldata:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123321Aa
      MYSQL_DATABASE: online.fdm.center
      MYSQL_USER: fdmuser
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}

  backend:
    build: ./
    image: home.4it.me:5000/ofc-server:latest
    command: yarn start
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - softmigration
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_AUTH_TOKEN: ${SERVER_AUTH_TOKEN}
      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN}
      MYSQL_URL: mysql://fdmuser:${DB_USER_PASSWORD}@db/online.fdm.center

  softmigration:
    image: node:10
    command: yarn migrate
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      MYSQL_URL: mysql://fdmuser:${DB_USER_PASSWORD}@db/online.fdm.center
