version: '3.1'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /opt/fdm_mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: online.fdm.center
      MYSQL_USER: fdmuser
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}

  backend:
    image: node:10
    command: yarn start
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - softmigration
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_AUTH_TOKEN: alUwi44C0i4qimidata3zEL4
      ADMIN_AUTH_TOKEN: viCAkEde948872suy1uzaqa7
      MYSQL_URL: mysql://fdmuser:${DB_USER_PASSWORD}@db/online.fdm.center

  softmigration:
    image: node:10
    command: yarn migrate
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      MYSQL_URL: mysql://fdmuser:${DB_USER_PASSWORD}@db/online.fdm.center

