
version: '3.1'
services:

  onlinefdmmigrate:
    image: home.4it.me:5000/ofc-server:latest
    command: yarn migrate -- --rebuild
    links:
      - db
    environment:
      MYSQL_URL: mysql://fdmuser:${DB_USER_PASSWORD}@db/online.fdm.center
