
version: '3.1'
services:

  onlinefdmmigrate:
    image: node:10
    command: yarn migrate -- --rebuild
    links:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      MYSQL_URL: mysql://fdmuser:${DB_USER_PASSWORD}@db/online.fdm.center
